// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI-DshdCaM8TlRxMNexpUml7rMpvlCsQc',
    appId: '1:328104110732:web:5f6dd4a1bd55c74c3ce9a9',
    messagingSenderId: '328104110732',
    projectId: 'loginapp-4b866',
    authDomain: 'loginapp-4b866.firebaseapp.com',
    storageBucket: 'loginapp-4b866.appspot.com',
    measurementId: 'G-J4WCM8YQ7H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZiSGd5HslNQcKKkD1FRfsTcKAhuV5DUA',
    appId: '1:328104110732:android:c472dcb807016a643ce9a9',
    messagingSenderId: '328104110732',
    projectId: 'loginapp-4b866',
    storageBucket: 'loginapp-4b866.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyC5-pnybomg_IDkF6qmbSlQ_wmBp7b4w',
    appId: '1:328104110732:ios:bf97f4206bd2b1273ce9a9',
    messagingSenderId: '328104110732',
    projectId: 'loginapp-4b866',
    storageBucket: 'loginapp-4b866.appspot.com',
    iosBundleId: 'com.example.flutterApplication4',
  );
}
